steps:
  - label: "fossa analyze"
    agents:
      queue: "buildkite-gcp-medium"
    command: ".buildkite/scripts/fossa.sh"
  - label: "Lint Check"
    agents:
      queue: "buildkite-gcp-medium"
    command: ".buildkite/scripts/lint.sh"
    plugins:
      - docker-compose#v3.0.0:
          run: unit-test-test-service
          config: docker/buildkite/docker-compose.yaml
  - label: ":java: Unit test with test services"
    agents:
      queue: "buildkite-gcp-large"
    command: "./gradlew --no-daemon test jacocoTestReport"
    artifact_paths:
      - "build/reports/jacoco/test/*.xml"
    timeout_in_minutes: 15
    retry:
      automatic:
        - exit_status: "*"
          limit: 3
    plugins:
      - docker-compose#v3.0.0:
          run: unit-test-test-service
          config: docker/buildkite/docker-compose.yaml

  - label: ":java: Unit test with docker services sticky on"
    agents:
      queue: "buildkite-gcp-large"
    command: "./gradlew --no-daemon test"
    timeout_in_minutes: 15
    retry:
      automatic:
        - exit_status: "*"
          limit: 3
    plugins:
      - docker-compose#v3.0.0:
          run: unit-test-docker-sticky-on
          config: docker/buildkite/docker-compose.yaml

  - label: ":java: Unit test with docker services sticky off"
    agents:
      queue: "buildkite-gcp-large"
    command: "./gradlew --no-daemon test"
    timeout_in_minutes: 15
    retry:
      automatic:
        - exit_status: "*"
          limit: 3
    plugins:
      - docker-compose#v3.0.0:
          run: unit-test-docker-sticky-off
          config: docker/buildkite/docker-compose.yaml
  - wait

  - label: ":java: Report test coverage"
    agents:
      queue: "buildkite-gcp-large"
    command: ".buildkite/scripts/coverage.sh"
    retry:
      automatic:
        - exit_status: "*"
          limit: 3
    plugins:
      - docker-compose#v3.0.0:
          run: test-coverage-report
          config: docker/buildkite/docker-compose.yaml
