container:
  kubernetes: &kubernetes
    sidecars:
    - image: us-west1-docker.pkg.dev/ci-compute/buildkite-images/buildkite-dind:v1
      command:
      - |-
        dockerd-entrypoint.sh
      volumeMounts:
        - mountPath: /var/run/
          name: docker-sock
      securityContext:
        privileged: true
        allowPrivilegeEscalation: true
    mirrorVolumeMounts: true # CRITICAL: this must be at the same indentation level as sidecars
    podSpec: &podSpec
      containers:
        - &commandContainer
          image: us-west1-docker.pkg.dev/ci-compute/buildkite-images/buildkite-command-container:v2
          command:
          - |-
            echo "Command step was not overridden."
            exit 1
          volumeMounts:
            - mountPath: /var/run/
              name: docker-sock
          resources:
            requests:
              cpu: 12000m
              memory: 55G
      volumes:
      - name: docker-sock
        emptyDir: {}

steps:
  - label: "fossa analyze"
    agents:
      queue: "buildkite-gcp-medium-helm"
    command: ".buildkite/scripts/fossa.sh"

  - label: "Lint Check"
    agents:
      queue: "buildkite-gcp-medium-helm"
    plugins:
      - kubernetes:
          <<: *kubernetes
          podSpec:
            <<: *podSpec
            containers:
              - <<: *commandContainer
                command:
                - |-
                  .buildkite/scripts/lint.sh
      - docker-compose#v3.0.0:
          run: unit-test-test-service
          config: docker/buildkite/docker-compose.yaml

  - label: ":java: Unit test with test services"
    agents:
      queue: "buildkite-gcp-large-helm"
    artifact_paths:
      - "build/reports/jacoco/test/*.xml"
    timeout_in_minutes: 30
    retry:
      automatic:
        - exit_status: "*"
          limit: 3
    plugins:
      - kubernetes:
          <<: *kubernetes
          podSpec:
            <<: *podSpec
            containers:
              - <<: *commandContainer
                command:
                - |-
                  ./gradlew --no-daemon test jacocoTestReport
      - docker-compose#v3.0.0:
          run: unit-test-test-service
          config: docker/buildkite/docker-compose.yaml

  - label: ":java: Unit test with docker services sticky on"
    agents:
      queue: "buildkite-gcp-large-helm"
    timeout_in_minutes: 30
    retry:
      automatic:
        - exit_status: "*"
          limit: 3
    plugins:
      - kubernetes:
          <<: *kubernetes
          podSpec:
            <<: *podSpec
            containers:
              - <<: *commandContainer
                command:
                - |-
                  ./gradlew --no-daemon test
      - docker-compose#v3.0.0:
          run: unit-test-docker-sticky-on
          config: docker/buildkite/docker-compose.yaml

  - label: ":java: Unit test with docker services sticky off"
    agents:
      queue: "buildkite-gcp-large-helm"
    timeout_in_minutes: 30
    retry:
      automatic:
        - exit_status: "*"
          limit: 3
    plugins:
      - kubernetes:
          <<: *kubernetes
          podSpec:
            <<: *podSpec
            containers:
              - <<: *commandContainer
                command:
                - |-
                  ./gradlew --no-daemon test
      - docker-compose#v3.0.0:
          run: unit-test-docker-sticky-off
          config: docker/buildkite/docker-compose.yaml

  - wait

  - label: ":java: Report test coverage"
    agents:
      queue: "buildkite-gcp-large-helm"
    retry:
      automatic:
        - exit_status: "*"
          limit: 3
    plugins:
      - kubernetes:
          <<: *kubernetes
          podSpec:
            <<: *podSpec
            containers:
              - <<: *commandContainer
                command:
                - |-
                  .buildkite/scripts/coverage.sh
      - docker-compose#v3.0.0:
          run: test-coverage-report
          config: docker/buildkite/docker-compose.yaml
