version: '3.5'

services:
  cassandra:
    image: cassandra:4.1.3
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 12000M
    ports:
      - "9042:9042"

  statsd:
    image: hopsoft/graphite-statsd
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1024M
    ports:
      - "8080:80"
      - "2003:2003"
      - "8125:8125"
      - "8126:8126"

  cadence:
    image: ubercadence/server:master-auto-setup
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 8192M
    ports:
      - "7933:7933"
      - "7934:7934"
      - "7935:7935"
      - "7939:7939"
    environment:
      - "CASSANDRA_SEEDS=cassandra"
      - "STATSD_ENDPOINT=statsd:8125"
    depends_on:
      - cassandra
      - statsd

  unit-test-docker-sticky-off:
    build:
      context: ../../
      dockerfile: ./docker/buildkite/Dockerfile
    command: "./gradlew --no-daemon test"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 8192M
    environment:
      - "USER=unittest"
      - "CADENCE_SEEDS=cadence"
      - "USE_DOCKER_SERVICE=true"
      - "STICKY_OFF=true"
    depends_on:
      - cadence
    volumes:
      - "../../:/cadence-java-client"

  unit-test-docker-sticky-on:
    build:
      context: ../../
      dockerfile: ./docker/buildkite/Dockerfile
    command: "./gradlew --no-daemon test"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 8192M
    environment:
      - "USER=unittest"
      - "CADENCE_SEEDS=cadence"
      - "USE_DOCKER_SERVICE=true"
      - "STICKY_OFF=false"
    depends_on:
      - cadence
    volumes:
      - "../../:/cadence-java-client"

  unit-test-test-service:
    build:
      context: ../../
      dockerfile: ./docker/buildkite/Dockerfile
    command: "./gradlew --no-daemon test"
    environment:
      - "USER=unittest"
      - "USE_DOCKER_SERVICE=false"
    volumes:
      - "../../:/cadence-java-client"

  test-coverage-report:
    build:
      context: ../../
      dockerfile: ./docker/buildkite/Dockerfile
    command: "./gradlew --no-daemon test"
    environment:
      - "USER=unittest"
      - "USE_DOCKER_SERVICE=false"
      - CI
      - BUILDKITE
      - BUILDKITE_AGENT_ACCESS_TOKEN
      - BUILDKITE_JOB_ID
      - BUILDKITE_BUILD_ID
      - BUILDKITE_BUILD_NUMBER
      - BUILDKITE_BRANCH
      - BUILDKITE_BUILD_URL
      - BUILDKITE_PROJECT_SLUG
      - BUILDKITE_COMMIT
      - BUILDKITE_PULL_REQUEST
      - BUILDKITE_TAG
      - BUILDKITE_REPO
      - BUILDKITE_BUILD_CREATOR
      - BUILDKITE_BUILD_CREATOR_EMAIL
      - BUILDKITE_BUILD_CREATOR_TEAMS
      - BUILDKITE_PULL_REQUEST_REPO
      - COVERALLS_REPO_TOKEN
    volumes:
      - "../../:/cadence-java-client"
